using System;
using System.Collections.Generic;

namespace CovertingDicom.Models
{
    public partial class Echo
    {
        public int EIncId { get; set; }
        public int? ERepIncDet { get; set; }
        public DateTime? EDate { get; set; }
        public float? EBsa { get; set; }
        public byte? EHr { get; set; }
        public byte? EBp1 { get; set; }
        public byte? EBp2 { get; set; }
        public string? ETape { get; set; }
        public string? EDisk { get; set; }
        public string? ELa { get; set; }
        public byte? ELa2d1 { get; set; }
        public byte? ELa2d2 { get; set; }
        public string? EAoRoot { get; set; }
        public string? EAoAsc { get; set; }
        public string? EIvs { get; set; }
        public float? ELvedd { get; set; }
        public float? ELvesd { get; set; }
        public string? EPw { get; set; }
        public float? EMass { get; set; }
        public float? EFs { get; set; }
        public float? EEf { get; set; }
        public byte? ERa2d1 { get; set; }
        public byte? ERa2d2 { get; set; }
        public string? ERv { get; set; }
        public string? ERv2d { get; set; }
        public string? EAvArGrade { get; set; }
        public string? EAvArPht { get; set; }
        public string? EAvSysPv { get; set; }
        public string? EAvPg { get; set; }
        public string? EAvMg { get; set; }
        public string? EAvAsVti { get; set; }
        public string? EAvArea { get; set; }
        public string? EAvLvotDiam { get; set; }
        public string? EAvLvotVel { get; set; }
        public string? EAvLvotVti { get; set; }
        public string? EAvSv { get; set; }
        public string? EAvCo { get; set; }
        public string? EAvCi { get; set; }
        public string? EMvMrGrade { get; set; }
        public string? EMvPg { get; set; }
        public string? EMvMg { get; set; }
        public string? EMvMva2d { get; set; }
        public string? EMvMvaPht { get; set; }
        public string? EMvMvaCe { get; set; }
        public string? EMvPht { get; set; }
        public string? EMvVti { get; set; }
        public string? EMvDpDt { get; set; }
        public string? ETvTrGrade { get; set; }
        public string? ETvTrPg { get; set; }
        public string? ETvPg { get; set; }
        public string? ETvMg { get; set; }
        public string? ETvTvaPht { get; set; }
        public string? ETvTvaCe { get; set; }
        public string? ETvPht { get; set; }
        public string? ETvVti { get; set; }
        public string? EPvPrGrade { get; set; }
        public string? EPvPrEdg { get; set; }
        public string? EPvSysPv { get; set; }
        public string? EPvPg { get; set; }
        public string? EPvMg { get; set; }
        public string? EPvRvotDiam { get; set; }
        public string? EPvRvotVel { get; set; }
        public string? EEWave { get; set; }
        public string? EAWave { get; set; }
        public string? EEA { get; set; }
        public string? EDt { get; set; }
        public string? EIvrt { get; set; }
        public string? EMiaWidth { get; set; }
        public string? EValsalvaEA { get; set; }
        public string? EPulmonaryVeins { get; set; }
        public string? ESD { get; set; }
        public string? EPvaWidth { get; set; }
        public string? ETdiE { get; set; }
        public string? ETdiEA { get; set; }
        public string? EMaLat { get; set; }
        public string? EMaMed { get; set; }
        public string? ETaLat { get; set; }
        public string? EManW { get; set; }
        public string? ETanW { get; set; }
        public string? EPericardium { get; set; }
        public byte? EPleuralEffusion { get; set; }
        public byte? EIvcCollapse { get; set; }
        public byte? EIvcDilated { get; set; }
        public string? EMrap { get; set; }
        public string? ERvsp { get; set; }
        public string? EPadp { get; set; }
        public string? ELvedp { get; set; }
        public string? EPcwp { get; set; }
        public string? EQpQs { get; set; }
        public string? ELvDimension { get; set; }
        public string? ELvSystolicFunction { get; set; }
        public string? ELvWallMotion { get; set; }
        public string? ELvDiastolicFunction { get; set; }
        public string? ERightVentricle { get; set; }
        public string? EAtria { get; set; }
        public string? EAorticValve { get; set; }
        public string? EMitralValve { get; set; }
        public string? ETricuspidValve { get; set; }
        public string? EPulmonicValve { get; set; }
        public string? EGreatVessels { get; set; }
        public string? EPericardiumPleural { get; set; }
        public string? EShunts { get; set; }
        public string? EOthers { get; set; }
    }
}
